### PR TITLE
Improves the "everywhere else" usage instructions.

### PR DESCRIPTION
**Pull request by oblitum**
Improves the installation instructions of the "everywhere else" section
describing usage for Qt compiled from latest repository sources.

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks, but I'm afraid these instructions are not for "everywhere else". It's one more example that works in specific circumstances. If you'd like to add instructions that work in a real environment not yet listed, that'd be welcome, but otherwise we already have examples right above that last note that can be used as guidelines.

**Comment by oblitum** [comment]
Ok. I think these are good general *nix guidelines for using from sources that I missed, the others are package and/or system specific and somewhat not clear how to map. I myself, as I have everything from repo, started by `go get`, got errors and figured out from them what I needed to do.

**Comment by niemeyer** [comment]
Ok, but what's your environment?  We can have instructions for it as well.  It's better to have realistic instructions that are known to work on a given environment than to provide wildcard ones that will fail in some cases (MacOS is a *nix, and these instructions do not work there, for example).

**Comment by oblitum** [comment]
my environment is ubuntu using qt compiled with clang from sources, and go too compiled from repository sources. I think the same would apply for OS X too, if one is using stuff from repository sources (as I used to do on OS X).

**Comment by oblitum** [comment]
The Windows setup is the simple one by providing raw path configurations, the others are a bit cluttered with package manager information and there's no simple notice about setting `PKG_CONFIG_PATH` and `CGO_CPPFLAGS`  paths for *nix usage in general, which I think may be helpful.

**Pull request closed without merging**
