### PR TITLE
Make sure context.file is not null before calling strlen

### PR DESCRIPTION
**Pull request by tsdgeos**
Fixes crash in ciborium

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks for the fix. Can you please sign up the contributors agreement so the fix may be integrated:

http://www.ubuntu.com/legal/contributors

Thanks!

**Comment by tsdgeos** [comment]
I work for canonical, so I don't need to sign that.

**Comment by tsdgeos** [comment]
You can check in https://launchpad.net/~aacid

**Comment by niemeyer** [comment]
Thanks!

**Pull request merged**
