### PR TITLE
Change to use github.com/go-gl/gl for OpenGL calls

### PR DESCRIPTION
**Pull request by tmc**
This increases portability and plays well with others

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks, I appreciate your interest, and would love to have your help on more of this.

Unfortunately, unless I'm missing some recent development, this won't work. Using go-gl was the first thing I tried, and if you start trying to wrap things like glGenBuffers, you'll notice it fails because the symbol names available match the real function names, which differ from those expected by go-gl due to glew conventions. Historical record on it: http://goo.gl/9UYjEf

In the next few weeks, I'm also planning to move on from using the bare symbols to the ones offered by Qt since 5.1. This will increase portability significantly, and it might also help people being more conscious about which GL version they're using.

If you're interested in collaboration, please join the mailing list and let's talk.

**Comment by tmc** [comment]
Ah, I didn't realize that would be a problem. The examples work fine with this change. _Shrug_

**Comment by niemeyer** [comment]
Yeah, they work fine because glGenBuffers was recently dropped to reduce the linking workflow for people in other operating systems. Once we do the improvements mentioned, we'll have these additional extensions, and will have trivial portability. Again, your help is welcome.

**Comment by niemeyer** [comment]
Sorry, ticket referenced the wrong issue. It was aimed at #47.

**Pull request closed without merging**
