### PR TITLE
Fix samples for changes in qml.Object

### PR DESCRIPTION
**Pull request by oblitum**
qml.Object is now an interface, this updates the samples according so
that they keep running.

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks!  Can you please sign the contributor agreement at:

http://www.canonical.com/contributors

**Comment by oblitum** [comment]
@niemeyer I'll but, this project is not listed in the list of covered projects... ( ? )

**Comment by niemeyer** [comment]
It is also covered, and no need to mail anyone besides reading it to make sure you agree and following the online procedure to sign.

**Comment by oblitum** [comment]
I've agreed. At the end they promised to enter in contact soon.

**Comment by niemeyer** [comment]
Thanks!

**Pull request merged**
